name: CI

on: [push]

jobs:
  Build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v1    
    - name: Build with MSBuild
      run: |
        & "${env:ProgramFiles(x86)}\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\msbuild.exe"
